version: '2'

services:
  backend:
    build: .
    restart: always
    container_name: tickytook-backend
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 82:4004
